version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: infra/Dockerfile
    container_name: manuweaver-backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CROSSREF_MAILTO=${CROSSREF_MAILTO}
      - OPENALEX_BASE=${OPENALEX_BASE}
      - NCBI_API_KEY=${NCBI_API_KEY}
      - ARXIV_BASE=${ARXIV_BASE}
      - REDIS_URL=${REDIS_URL}
      - STORAGE_ROOT=/data/projects
      - ALLOWED_TEX_COMMANDS=${ALLOWED_TEX_COMMANDS}

      - LLM_PROVIDER=${LLM_PROVIDER:-stub}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3}
      - LMSTUDIO_BASE_URL=${LMSTUDIO_BASE_URL:-http://host.docker.internal:1234/v1}
      - LMSTUDIO_MODEL=${LMSTUDIO_MODEL:-llama3}

    volumes:
      - storage:/data
      - ./templates:/app/templates
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: infra/Dockerfile
    container_name: manuweaver-worker
    command: ["celery", "-A", "backend.app.tasks.celery_app", "worker", "-l", "info"]
    environment:
      - REDIS_URL=${REDIS_URL}
      - STORAGE_ROOT=/data/projects

      - LLM_PROVIDER=${LLM_PROVIDER:-stub}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3}
      - LMSTUDIO_BASE_URL=${LMSTUDIO_BASE_URL:-http://host.docker.internal:1234/v1}
      - LMSTUDIO_MODEL=${LMSTUDIO_MODEL:-llama3}

    volumes:
      - storage:/data
      - ./templates:/app/templates
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: infra/Dockerfile.frontend
    container_name: manuweaver-frontend
    environment:
      - NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE:-http://localhost:8000}
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: manuweaver-redis
    ports:
      - "6379:6379"

volumes:
  storage:
